CREATE TABLE itenpedido( 
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
ID_PRODUTO INT NOT NULL, 
ID_PEDIDO INT NOT NULL, 
VALOR DECIMAL(10,2) NOT NULL,
QTDE INT NOT NULL,
CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES produto (id),
CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES pedido (id)
)