CREATE TABLE itenpedido( 
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
id_produto INT NOT NULL, 
id_pedido INT NOT NULL, 
valor DECIMAL(10,2) NOT NULL,
qtde INT NOT NULL,
CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (id_produto) REFERENCES produto (id),
CONSTRAINT FK_ID_PEDIDO FOREIGN KEY (id_pedido) REFERENCES pedido (id)
)