CREATE TABLE OBJETO (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
DESCRICAO VARCHAR(100) NOT NULL,
PLCACA VARCHAR(100) NULL,
ANO VARCHAR(50) NULL,
MODELO VARCHAR(10) NULL,
OBSERVACAO VARCHAR(100) NULL
)