CREATE TABLE OBJETO (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
descricao VARCHAR(100) NOT NULL,
placa VARCHAR(100) NULL,
ano VARCHAR(50) NULL,
modelo VARCHAR(10) NULL,
observacao VARCHAR(100) NULL
)