CREATE TABLE usuario(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
login VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL,
foto VARCHAR(150) NOT NULL,
status CHAR(1) NOT NULL)